### ISSUE TITLE
API error with limit=0

### ISSUE THREAD

**Issue by sebbASF** [Humbedooh/clc#33]
https://clc.diversity.apache.org/api/details.json?project=www-site.git&limit=0 gives

API error occurred: 
Traceback (most recent call last):

  File "main.py", line 130, in handle_request
    output = await self.handlers[handler].exec(self, session, indata)

  File "/x1/clc/server/endpoints/details.py", line 103, in process
    yml = yml[:limit]

TypeError: 'NoneType' object is not subscriptable

**Comment by sebbASF** [comment]
The website is still crashing

**Comment by sebbASF** [comment]
As does the Demo site:
https://clcdemo.net/api/details.json?project=incubator-ponymail-foal.git&limit=0
